---

- name: Install celery with redis option
  pip: virtualenv={{ base_dir }}/.virtualenvs/{{ project_name }}
       name=celery[redis]
  tags: install celery

- name: Create the celery startup service
  become: yes
  template: src=roles/deploy/templates/celery.service.j2 dest=/etc/systemd/system/celery.service
            backup=yes owner=nginx group=nginx mode=0750
  tags: install celery

- name: Create the celerybeat startup service
  become: yes
  template: src=roles/deploy/templates/celerybeat.service.j2 dest=/etc/systemd/system/celerybeat.service
            backup=yes owner=nginx group=nginx mode=0750
  tags: install celery

