---

- name: Install PostgreSQL (install via yum as per advice on postgresql website)
  become: yes
  become_user: root
  yum: name=http://yum.postgresql.org/9.5/redhat/rhel-7-x86_64/pgdg-redhat95-9.5-2.noarch.rpm state=installed
  tags: install database

- name: Install PostgreSQL 9.5 (install via yum as per advice on postgresql website)
  become: yes
  become_user: root
  yum: name={{ item }} state=installed
  with_items:
    - postgresql95-server
    - postgresql95-contrib
    - postgresql95-devel
    - python-psycopg2
  tags: install database

- name: Initialise database with options
  become: yes
  become_user: root
  shell: PGSETUP_INITDB_OPTIONS='--encoding=UTF8 --data-checksums' /usr/pgsql-9.5/bin/postgresql95-setup initdb
           creates=/var/lib/pgsql/9.5/data/postgresql.conf
  tags: install database

- name: add postgres bin path to system path
  become: yes
  become_user: root
  shell: echo 'export PATH=$PATH:/usr/pgsql-9.5/bin' > '/etc/profile.d/postgres.sh'
  tags: install database

- name: postgres performance tweaks
  become: yes
  become_user: postgres
  blockinfile:
    dest: /var/lib/pgsql/9.5/data/postgresql.conf
    block: |
      listen_addresses = '*'
      log_destination = 'csvlog'
      logging_collector = on
      log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
      log_rotation_age = 1d
      log_rotation_size = 10MB
      log_min_duration_statement = 50
      log_checkpoints = on
      log_connections = on
      log_disconnections = on
      log_lock_waits = on
      log_temp_files = 0
      shared_buffers = 128MB             # should be 25% of RAM (up to max of 8GB)
      work_mem = 32MB                    # should be 2 * RAM / max_connections
      maintenance_work_mem = 64MB        # should be 10% of RAM (up to max of 1GB)
      effective_cache_size = 256MB       # should be RAM / 2
      max_connections = 64               # should be no more than 400
      wal_buffers = 16MB                 # should be fixed at 16MB
      checkpoint_completion_target = 0.9 # should be fixed at 0.9
      checkpoint_timeout = 10min         # should be 10-30m (restart takes ~ 20% of this time)
      effective_io_concurrency = 1       # set to number of I/O channels
      random_page_cost = 1.1             # RAID 10 = 3, SAN=2, Amazon EBS = 1
  tags: install database

- name: postgresql should allow access from anywhere
  become: yes
  become_user: postgres
  lineinfile: dest=/var/lib/pgsql/9.5/data/pg_hba.conf backup=yes
              regexp="^0.0.0.0"
              line="host    all           all                0.0.0.0/0             md5" state=present
  tags: install database

- name: postgresql should allow access via md5 not ident
  become: yes
  become_user: postgres
  replace: dest=/var/lib/pgsql/9.5/data/pg_hba.conf regexp='ident' replace='md5' backup=yes
  tags: install database

- name: Ensure the PostgreSQL service is running
  become: yes
  become_user: root
  service: name=postgresql-9.5 state=started enabled=yes
  tags: install database

- name: Ensure database is created
  become: yes
  become_user: postgres
  postgresql_db: name={{ db_name }} state=present
  tags: install database

- name: Ensure django user has access to the database
  become: yes
  become_user: postgres
  postgresql_user: db={{ db_name }} name={{ db_user }} password={{ db_password }} priv=ALL role_attr_flags=CREATEDB state=present
  tags: install database

- name: Start firewalld to add new rules
  become: yes
  become_user: root
  service: name=firewalld state=restarted
  tags: install database

- name: Allow port 5432 through firewall
  become: yes
  become_user: root
  firewalld: port=5432/tcp zone=public immediate=yes permanent=true state=enabled
  tags: install database
