---
#################### Install linux packages, setup linux and user

- name: Install RPM forge repo (for htop)
  become: yes
  yum: name=http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el7.rf.x86_64.rpm state=present
  tags: install linux

- name: install the pg_top rpm from a remote repo
  become: yes
  yum: name=http://yum.postgresql.org/9.5/redhat/rhel-7-x86_64/pgdg-redhat95-9.5-2.noarch.rpm state=present
  tags: install linux

- name: Upgrade all existing packages
  become: yes
  yum: name=* state=latest
  tags: install linux

- name: Ensure key linux packages are installed and the latest versions
  become: yes
  yum: name={{ item }} state=latest
  with_items:
    - bash
    - openssl       # required for python3, pip
    - openssl-devel # required for python3, pip
    - libffi-devel  # required for pip installs (cryptography)
    - ntp
    - git
    - gcc           # required for amazon ec2 redhat 7.2
    - firewalld     # required for amazon ec2 redhat 7.2
    - htop          # system performance
    - pg_top95      # database performance
    - ncurses-devel # required for uwsgitop (includes curses in standard libary)
    - sysstat       # system performance monitoring
    - perl-App-cpanminus # for pgbadger perl MCPAN installs
    - perl-CPAN     # for pgbadger perl MCPAN installs
  tags: install linux

- name: Change SELINUX to permissive
  become: yes
  selinux: policy=targeted state=permissive
  tags: install linux

- name: Set {{ ansible_user }} directory to be group executable (for nginx access)
  file: path={{ base_dir }} state=directory mode="g=rx"
  tags: install linux

- name: Create {{ project_name }} directory if not localhost
  file: path={{ project_name }} state=directory mode=0750
  when: inventory_hostname != "localhost.localdomain"
  tags: install linux

- name: install project environment file .{{ project_name }}.env
  template: src=../deploy/templates/project.conf.j2
            dest="{{ project_env }}" force=yes
  tags: install linux

- name: Add environment variable to bashrc (not to bash profile as pycharm etc doesnt login)
  become: yes
  blockinfile:
    dest: "{{ base_dir }}/.bashrc"
    block: |
      set -a
      source /home/{{ ansible_user }}/.{{ project_name }}.env
      set +a
  tags: install linux

- name: Add shortcuts to bash_profile to save time on login
  become: yes
  blockinfile:
    dest: "{{ base_dir }}/.bash_profile"
    block: |
      export PS1='\[\e]0;\w\a\]\[\e[36m\]\u@\h: \[\e[36m\]\w\[\e[0m\]\n\$ '
      source /usr/local/bin/virtualenvwrapper.sh
      alias m='./manage.py'
      workon {{ project_name }}
  tags: install linux

- name: Check current timezone
  become: yes
  shell: ll /etc/localtime | rev| cut -f1 -d"/" | rev
  register: current_zone
  changed_when: False
  tags: install linux

- name: Set Europe/London timezone
  become: yes
  file: src=/usr/share/zoneinfo/{{ timezone }}  dest=/etc/localtime state=link force=yes
  when: current_zone.stdout != '{{ timezone }}'
  tags: install linux

- name: restart ntp daemon
  become: yes
  service: name=ntpd state=restarted enabled=yes
  tags: install linux

- name: Shell script to update virtualbox guest additions (need to 'insert' cd via virtualbox first)
  blockinfile:
    dest: "{{ base_dir }}/VirtualBoxGuestAdditions.sh"
    create: yes
    mode: 0755
    block: |
      mkdir -p /media/cdrom
      mount /dev/cdrom /media/cdrom
      sh /media/cdrom/VBoxLinuxAdditions.run
  when: inventory_hostname == "localhost.localdomain"
  tags: install linux

- name: Set hostname
  become: yes
  hostname: name="{{ inventory_hostname }}"
  tags: install linux
