---

- name: Install nginx - Create nginx temp directory
  file: path="{{ base_dir }}/nginx" state=directory
  tags: install nginx
- name: Install nginx - Get nginx source
  get_url: url=http://nginx.org/download/nginx-{{ nginx_version }}.tar.gz
           dest="{{ base_dir }}/nginx/nginx.tar.gz" mode=0444
  tags: install nginx
- name: Install nginx - Unarchive nginx tarball
  unarchive: src="{{ base_dir }}/nginx/nginx.tar.gz" dest="{{ base_dir }}/nginx"
             owner={{ username }} copy=no creates={{ base_dir }}/nginx/nginx-{{ nginx_version }}
  tags: install nginx
- name: Install nginx - Configure
  command: ./configure --user=nginx --group=nginx --prefix=/etc/nginx
    --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf
    --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock
    --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log
    --with-http_ssl_module --with-http_v2_module
  args:
    chdir: "{{ base_dir }}/nginx/nginx-{{ nginx_version }}"
    creates: "{{ base_dir }}/nginx/nginx-{{ nginx_version }}/Makefile"
  tags: install nginx
- name: Install nginx - Make
  command: make
  args:
    chdir: "{{ base_dir }}/nginx/nginx-{{ nginx_version }}"
    creates: "{{ base_dir }}/nginx/nginx-{{ nginx_version}}/objs/nginx"
  tags: install nginx
- name: Install nginx - Make Install
  become: yes
  become_user: root
  command: make install
  args:
    chdir: "{{ base_dir }}/nginx/nginx-{{ nginx_version }}"
    creates: "/usr/local/bin/nginx"
  tags: install nginx

#- name: Install nginx repo
#  become: yes
#  become_user: root
#  yum:
#    name: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
#  tags: install nginx
#- name: Install Nginx
#  become: yes
#  become_user: root
#  yum: name=nginx state=installed
#  tags: install nginx
#- name: enable nginx
#  become: yes
#  become_user: root
#  service: name=nginx enabled=yes
#  tags: install nginx
#- name: Install nginx - link nginx to /usr/local/bin
#  become: yes
#  become_user: root
#  file: src=/usr/local/nginx/sbin/nginx dest=/usr/local/bin/nginx state=link force=yes
#  tags: install nginx

- name: Add vagrant group to nginx to enable nginx to read project source
  become: yes
  become_user: root
  lineinfile:
    dest: /etc/nginx/nginx.conf
    regexp: '^user  nginx'
    line: "user  nginx {{ username }};"
  tags: install nginx

- name: make nginx/conf.d directory if doenst already exist
  become: yes
  become_user: root
  file: path="/etc/nginx/conf.d" state=directory owner=nginx group=nginx
  tags: install nginx
- name: Add conf.d directory to nginx.conf if not already exists
  become: yes
  become_user: root
  lineinfile:
    dest: /etc/nginx/nginx.conf
    regexp: '^include /etc/nginx/conf.d'
    line: "include /etc/nginx/conf.d/*.conf;"
  tags: install nginx

- name: Create the master Nginx configuration file
  become: yes
  become_user: root
  template: src=nginxmaster.conf.j2 dest=/etc/nginx/nginx.conf
            owner=nginx group=nginx backup=yes force=yes
  tags: install nginx

- name: Create the nginx startup service if doesnt already exist
  become: yes
  become_user: root
  template: src=roles/deploy/templates/nginx.service.j2 dest=/etc/systemd/system/nginx.service
            backup=yes owner=nginx group=nginx mode=0750
  tags: install nginx
- name: enable nginx
  become: yes
  become_user: root
  service: name=nginx.service enabled=yes
  tags: install nginx

- name: Allow port 80 through firewall
  become: yes
  become_user: root
  firewalld: port=80/tcp permanent=true state=enabled
  tags: install nginx
- name: Allow port 443 through firewall
  become: yes
  become_user: root
  firewalld: port=443/tcp permanent=true state=enabled
  tags: install nginx
- name: Allow port 8000 through firewall
  become: yes
  become_user: root
  firewalld: port=8000/tcp permanent=true state=enabled
  tags: install nginx
- name: Restart firewalld to enable new rules
  become: yes
  become_user: root
  service: name=firewalld state=restarted
  tags: install nginx
