---

- name: Install PostgreSQL yum repository
  become: yes
  become_user: root
  yum: name=http://yum.postgresql.org/9.5/redhat/rhel-7-x86_64/pgdg-redhat95-9.5-2.noarch.rpm state=installed
  tags: install postgresql

- name: Install PostgreSQL (install via yum as per advice on postgresql website)
  become: yes
  become_user: root
  yum: name={{ item }} state=installed
  with_items:
    - postgresql95-server
    - postgresql95-contrib
    - postgresql95-devel
    - python-psycopg2
  tags: install postgresql

- name: add postgres bin path to system path (create postgres.sh file)
  become: yes
  become_user: root
  lineinfile: dest=/etc/profile.d/postgres.sh state=present create=yes
              line='export PATH=$PATH:/usr/pgsql-9.5/bin'
  tags: install postgresql

- name: Initialise database with options
  become: yes
  become_user: root
  shell: PGSETUP_INITDB_OPTIONS='--data-checksums' /usr/pgsql-9.5/bin/postgresql95-setup initdb
           creates=/var/lib/pgsql/9.5/data/postgresql.conf
  tags: install postgresql

- name: add additional postgresql.conf file
  become: yes
  become_user: postgres
  lineinfile:
    dest: /var/lib/pgsql/9.5/data/postgresql.conf
    line: "include = 'postgresql-custom.conf'"
  tags: install postgresql

- name: postgres performance and logging config to postgresql-custom.conf
  become: yes
  become_user: postgres
  template: src=../deploy/templates/postgresql-custom.conf.j2
            dest=/var/lib/pgsql/9.5/data/postgresql-custom.conf force=yes
  notify:
    - restart postgresql
  tags: install postgresql

- name: postgresql - setup security in pg_hba.conf (insertbefore to override default settings)
  become: yes
  become_user: postgres
  blockinfile:
    dest: /var/lib/pgsql/9.5/data/pg_hba.conf
    insertafter: 'TYPE'
    block: |
      local   all             postgres                              peer
      local   all             {{ db_user }}                                md5
      host    all             all             0.0.0.0/0             md5
      host    all             all             ::1/128               md5
  notify:
    - restart postgresql
  tags: install postgresql

- name: Ensure the PostgreSQL service is running
  become: yes
  become_user: root
  service: name=postgresql-9.5 state=started enabled=yes
  tags: install postgresql

- name: Create database
  become: yes
  become_user: postgres
  postgresql_db: name={{ db_name }} state=present
  tags: install postgresql

- name: Ensure django user has access to the database with all privileges
  become: yes
  become_user: postgres
  postgresql_user: db={{ db_name }} name={{ db_user }} password={{ db_password }} priv=ALL role_attr_flags=CREATEDB state=present
  tags: install postgresql

- name: Start firewalld to add new rules
  become: yes
  become_user: root
  service: name=firewalld enabled=yes state=started
  tags: install postgresql

- name: Allow port 5432 through firewall
  become: yes
  become_user: root
  firewalld: port=5432/tcp zone=public immediate=yes permanent=true state=enabled
  tags: install postgresql


- name: Install pgbadger perl prerequisites
  become: yes
  become_user: root
  cpanm: name=Text::CSV_XS system_lib=yes
  tags: install pgbadger

- name: Install pgbadger log analyzer - Create temp directory
  file: path="{{ base_dir }}/pgbadger" state=directory
  tags: install pgbadger

- name: Install pgbadger log analyzer - get tarball
  get_url: url=https://github.com/dalibo/pgbadger/archive/v8.0.tar.gz
           dest="{{ base_dir }}/pgbadger/pgbadger-8.0.tar.gz" mode=0444
  tags: install pgbadger

- name: Install pgbadger log analyzer - Unarchive tarball
  unarchive: src="{{ base_dir }}/pgbadger/pgbadger-8.0.tar.gz" dest="{{ base_dir }}/pgbadger/"
             owner={{ ansible_user }} copy=no creates={{ base_dir }}/pgbadger/pgbadger-8.0
  tags: install pgbadger

- name: Install pgbadger - Configure makefile
  command: perl Makefile.PL
  args:
    chdir: "{{ base_dir }}/pgbadger/pgbadger-8.0"
    creates: "{{ base_dir }}/pgbadger/pgbadger-8.0/Makefile"
  tags: install pgbadger

- name: Install pgbadger - Make
  command: make
  args:
    chdir: "{{ base_dir }}/pgbadger/pgbadger-8.0"
    creates: "{{ base_dir }}/pgbadger/pgbadger-8.0/blib/script/pgbadger"
  tags: install pgbadger

- name: Install pgbadger - Make Install
  become: yes
  become_user: root
  args:
    chdir: "{{ base_dir }}/pgbadger/pgbadger-8.0"
    creates: "/usr/local/bin/pgbadger"
  command: make install
  tags: install pgbadger
