---

- name: Install redis - make temp redis directory
  file: path="{{ base_dir }}/redis" state=directory
  tags: install redis
- name: Install redis - Download from redis website
  get_url: url=http://download.redis.io/releases/redis-{{ redis_version }}.tar.gz
           dest="{{ base_dir }}/redis/redis.tar.gz" mode=0444
  tags: install redis
- name: Install redis - Unarchive redis tarball
  unarchive: src="{{ base_dir }}/redis/redis.tar.gz" dest="{{ base_dir }}/redis"
             owner={{ ansible_user }} copy=no creates={{ base_dir }}/redis/redis-{{ redis_version }}
  tags: install redis
- name: Install redis - make
  command: make
  args:
    chdir: "{{ base_dir }}/redis/redis-{{ redis_version }}"
    creates: "{{ base_dir }}/redis/redis-{{ redis_version }}/src/redis-server"
  tags: install redis

- name: Install redis - make Install
  become: yes
  command: make install
  args:
    chdir: "{{ base_dir }}/redis/redis-{{ redis_version }}"
    creates: /usr/local/bin/redis-server
  tags: install redis

- name: Create the redis startup service
  become: yes
  template: src=roles/deploy/templates/redis.service.j2 dest=/etc/systemd/system/redis.service
            backup=yes owner=nginx group=nginx mode=0750
  tags: install redis
