---
######### FIX POSTGRESS NETOWRK ACCESS AND RE-TEST DJANGO CONSOLE
######### install redis from website, get uwsgi working, setup remote python interpreter (check fabfile too)
######### add hosts - development, staging, production and setup amazon EC2

####################

#- name: Pull {{ project_name }} source from the repository.
#  become_user: "{{ username }}"
#  git: repo={{ project_repo }}
#       only_if: "$vm == 1"
#       dest=/{{ project_name }} version=master update=no accept_hostkey=True

#################### setup nginx config and restart

- name: Create the Nginx configuration file
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/nginx.conf backup=yes force=yes

- name: Add vagrant group to nginx to enable read of proj source
  lineinfile:
    dest: /etc/nginx/nginx.conf
    regexp: '^user  nginx'
    line: "user  nginx vagrant;"

- name: Copy ssl crt
  copy: src="../{{ project_name }}/settings/secret/ssl_secret.crt"
        dest=/etc/nginx/conf.d owner=nginx group=nginx
- name: Copy ssl key
  copy: src="../{{ project_name }}/settings/secret/ssl_secret.key"
        dest=/etc/nginx/conf.d owner=nginx group=nginx

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

#################### setup uwsgi config and restart

- name: Create the uwsgi configuration file
  template: src=emperor.ini.j2 dest=/etc/uwsgi/emperor.ini backup=yes owner=nginx force=yes

- name: enable uwsgi
  service: name=uwsgi.service enabled=yes

####################

- name: Setup {{ project_name }} virtualenv site packages in {{ base_dir }}/.virtualenvs/{{ project_name }}
  become_user: "{{ username }}"
  pip: virtualenv={{ base_dir }}/.virtualenvs/{{ project_name }}
       requirements="{{ project_path }}/requirements/local.txt"

####################

- name: Initialise Django - makemigrations
  become_user: "{{ username }}"
  shell: . /usr/local/bin/virtualenvwrapper.sh && workon BankValDj && ./manage.py makemigrations
  args:
    executable: /bin/bash
    chdir: /{{ project_path }}

#- name: Initialise Django - migrate
#  command: m migrate

#- name: Initialise Django - runserver
#  command: m runserver 0.0.0.0:8000

