---

- name: Install celery with redis option
  become_user: "{{ username }}"
  pip: virtualenv={{ base_dir }}/.virtualenvs/{{ project_name }}
       name=celery[redis]
  tags: install celery

###################

- name: Create the celery startup service
  become: yes
  become_user: root
  template: src=deploy/templates/celery.service.j2 dest=/etc/systemd/system/celery.service
            backup=yes owner=nginx group=nginx mode=0750
  tags: install celery

- name: enable celery service
  become: yes
  become_user: root
  service: name=celery.service enabled=yes
  tags: install celery

- name: Create the celerybeat startup service
  become: yes
  become_user: root
  template: src=deploy/templates/celerybeat.service.j2 dest=/etc/systemd/system/celerybeat.service
            backup=yes owner=nginx group=nginx mode=0750
  tags: install celery

- name: enable celerybeat service
  become: yes
  become_user: root
  service: name=celerybeat.service enabled=yes
  tags: install celery

###################
