---
#################### Install linux packages, setup linux and user

- name: Ensure key linux packages are installed and the latest versions
  become: yes
  become_user: root
  yum: name={{ item }} state=latest
  with_items:
    - bash
    - openssl # required for python3, pip
    - openssl-devel # required for python3, pip
    - libffi-devel # required for pip installs (cryptography)
    - ntp
    - git
  tags: linux

- name: Set {{ username }} directory to be group executable (for nginx access)
  file: path={{ base_dir }} state=directory mode="g=rx"
  tags: linux

- name: Add exports/aliases to bash_profile
  become: yes
  become_user: root
  blockinfile:
    dest: "{{ base_dir }}/.bash_profile"
    block: |
      export WORKON_HOME=$HOME/.virtualenvs
      export PROJECT_HOME=$HOME
      source /usr/local/bin/virtualenvwrapper.sh
      alias m='./manage.py'
      alias celw='celery -A BankValDj worker --loglevel=INFO'
      export PYTHONPATH=PYTHONPATH:{{ base_dir }}/.virtualenvs/{{ project_name }}/lib/python3.5/site-packages/:{{ base_dir }}/BankValDj/:
  tags: linux

- name: Check current timezone
  become: yes
  become_user: root
  shell: ll /etc/localtime | rev| cut -f1 -d"/" | rev
  register: current_zone
  changed_when: False
  tags: linux

- name: Set Europe/London timezone
  become: yes
  become_user: root
  file: src=/usr/share/zoneinfo/{{ timezone }}  dest=/etc/localtime state=link force=yes
  when: current_zone.stdout != '{{ timezone }}'
  tags: linux