---

- name: Create a {{ project_name }} virtual machine via vagrant
  hosts: all
  become_method: sudo
  remote_user: vagrant

  roles:
    - { role: setup,  tags: fullsetup }
    - { role: deploy, tags: fulldeploy }
