- name: restart postgresql
  become: yes
  service: name=postgresql-9.5 state=restarted enabled=yes

- name: reload nginx
  become: yes
  service: name=nginx state=reloaded enabled=yes

- name: restart redis
  become: yes
  service: name=redis state=restarted enabled=yes

- name: restart uwsgi
  become: yes
  service: name=uwsgi.service state=restarted enabled=yes

- name: restart celery service
  become: yes
  service: name=celery state=restarted enabled=yes

- name: restart celerybeat service
  become: yes
  service: name=celerybeat state=restarted enabled=yes
